config/routes.rb
Kublog::Engine.routes.draw do
  root  :to => 'posts#index'
  
  resources :posts do
    resources :comments
    collection do
      post :check
      put  :check
    end
  end
  
  resources :notifications do
    collection do
      post :preview
    end
  end
    
  resources :images
  resources :categories
  match     '/:id', :to => 'posts#show', :as => 'quickie'
end

app/models/kublog/category.rb
# Non mandatory single category for a post
# implements friendly_id search and json defaults
# for ajax editing
module Kublog
  class Category < ActiveRecord::Base
    extend FriendlyId
    
    has_many  :posts,       :dependent => :nullify
    
    validates_presence_of   :name
    validates_uniqueness_of :name
    
    friendly_id             :name, :use => :slugged
    
    def to_s
      self.name.titleize
    end
    
    # Includes a path to the category by default
    # helps reference back to edited categories in
    # json requests
    def as_json(params={})
      params||={}
      super(params.merge!({:methods => [:path]}))
    end
    
    protected
    
    def path
      Engine.routes.url_helpers.category_path(self)
    end
    
  end
end

app/models/kublog/comment.rb
module Kublog
  class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
    
    validates_presence_of :body
    validate              :has_user_details
    
    default_scope   order('kublog_comments.created_at ASC')
    delegate        :admin?, :to => :user, :allow_nil => true
    
    after_create    :notify_author
    
    def author
      return self.author_name if self.user.nil?
      return self.user.to_s
    end
    
    def as_json(args={})
      args ||={}
      super(args.merge!({:methods => [:path, :author, :ftime, :admin?]}))
    end
    
    def path
      Engine.routes.url_helpers.post_comment_path(self.post, self)
    end
    
    def ftime
      I18n.l(self.created_at, :format => :short)
    end
    
    def email
      author_email || user.email
    end
    
    private
    
    def notify_author
      if CommentMailerManager.necessary_notifications?(self)
        Processor.work(DeliverComment.new(self.id))
      end
    end
    
    def has_user_details
      if self.user.nil?
        errors.add(:author_name,  :blank) if author_name.blank?
        errors.add(:author_email, :blank) if author_email.blank?
        errors.add(:author_email, :invalid) if !valid_author_email?
      end
    end
    
    def valid_author_email?
      self.author_email.to_s.match(/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i)
    end
    
  end
end

app/models/kublog/image.rb
module Kublog
  class Image < ActiveRecord::Base
    
    validates_presence_of :file
    
    mount_uploader  :file, FileUploader
    attr_accessible :file, :alt
    
    before_create     :set_default_alt
    before_validation :get_dimensions
    
    private
    
    def set_default_alt
      self.alt = file_url.match(/([\w|\b|\s\-]+)\.[png|jpg|gif|jpeg]+/)[1]
    end
    
    def get_dimensions
      self.file_width, self.file_height = `identify -format "%wx %h" #{self.file.path}`.split(/x/)
    end
    
  end
end

app/models/kublog/invited_author.rb
module Kublog
  class InvitedAuthor < ActiveRecord::Base
    belongs_to :post
    validates_presence_of :name, :email
    validate :correct_email_format

    def to_s
      name
    end

    private

    def correct_email_format
      unless email.to_s.match /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
        errors.add(:email, :invalid)
      end
    end
  end
end

app/models/kublog/notification.rb
module Kublog
  class Notification < ActiveRecord::Base    
    include Network::Email, Network::Facebook, Network::Twitter
    
    belongs_to :post
    
    # Presence of content should be responsability
    # Of each network module
    validates_presence_of :kind
    
    after_create  :deliver
    serialize     :roles, Array
    
    delegate      :title, :url, :to => :post
        
    def default?
      self.send "default_#{kind}"
    end
    
    private
    
    def deliver
      self.send "deliver_#{kind}" if respond_to?("deliver_#{kind}")
    end
    
  end
end

app/models/kublog/post.rb
# encoding: UTF-8
module Kublog
  class Post < ActiveRecord::Base
    extend FriendlyId
    
    #Associations
    belongs_to                :user,          :class_name => Kublog.author_class
    belongs_to                :category
    has_many                  :comments,      :dependent => :destroy
    has_many                  :notifications, :dependent => :nullify
    has_one                   :invited_author, :dependent => :destroy
    
    validates_presence_of     :title, :body, :user
    validate                  :body_with_content
    
    #Special Attributes
    friendly_id               :title, :use => :slugged
    attr_accessor             :want_invited_author
    
    #Scopes
    default_scope             order('kublog_posts.created_at DESC')
    
    accepts_nested_attributes_for :notifications
    accepts_nested_attributes_for :invited_author

    after_update              :check_for_deleted_invited_author
    
    def author
      invited_author ? invited_author : user
    end
    
    def to_s
      title
    end
    
    # Public Access to the Post
    def url
      unless new_record?
        Engine.routes.url_helpers.quickie_url(self, :host => Kublog.default_url_options[:host])
      end
    end
    
    def related_posts
      unless self.category.nil?
        self.category.posts.where('id != ?', self.id)
      end
    end
    
    private
    
    def body_with_content
      errors.add(:body, :blank) if blank_body?
    end
    
    # Weird regex identifies &nbsp; generated blank chars
    def blank_body?
      Sanitize.clean(self.body).gsub(/[ | ]/, '').blank? 
    end
    
    def check_for_deleted_invited_author
      invited_author.delete if invited_author && !want_invited_author
    end
  end
end

app/controllers/kublog/application_controller.rb
module Kublog
  class ApplicationController < ActionController::Base
    before_filter :require_admin
    
    helper_method :is_admin?
    helper_method :current_user #TODO: Delete me if you're using Devise
    
    def require_admin
      redirect_to root_path unless is_admin?
    end
    
    ## TODO: Fill in this method
    ## This method should return the logged in user or nil
    ## Define this whether or not you have it on your application controller
    ## Apps using Devise can skip this
    def current_user

    end
    
    ## TODO: Fill in this method
    ## Returns if the current user has admin privileges for the blog
    ## Define this whether or not you have the method on your application controller
    def is_admin?

    end
    
  end
end

app/controllers/kublog/categories_controller.rb
module Kublog
  class CategoriesController < ApplicationController
    
    skip_filter :require_admin, :only => [:show]
    
    def show
      @category = Category.find(params[:id])
      @presenter = PostsPresenter.new(@category)
      respond_to do |format|
        format.atom { render "/kublog/posts/index", :layout => false, :content_type => 'text/xml' }
        format.rss  { render "/kublog/posts/index", :layout => false, :content_type => 'text/xml' }
        format.html { render "/kublog/posts/index" }
      end
    end
    
    def create
      @category = Category.new(params[:category])
      respond_to do |format|
        if @category.save
          format.json { render :json => @category }
        else
          format.json { render :json => @category.errors.messages, :status => 'unprocessable_entity' }
        end
      end
    end
    
    def update
      @category = Category.find(params[:id])
      respond_to do |format|
        if @category.update_attributes(params[:category])
          format.json { render :json => @category }
        else
          format.json { render :json => @category.errors.messages, :status => 'unprocessable_entity' }
        end
      end
    end
    
    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      respond_to do |format|
        format.json{ render :json => @category }
      end
    end
    
  end
end

app/controllers/kublog/comments_controller.rb
module Kublog
  class CommentsController < ApplicationController
    
    skip_filter   :require_admin
    before_filter :set_comment_user, :only => [:create]
    
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(params[:comment])
      respond_to do |format|
        if @comment.save
          format.json { render :json => @comment}
        else
          format.json { render :json => @comment.errors.to_json, :status => :unprocessable_entity }
        end
      end
    end
    
    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      respond_to do |format|
        format.json{ render :json => @comment }
      end
    end
    
    private
    
    def set_comment_user
      if current_user
        params[:comment].merge!({:user => current_user})
      end
    end
    
  end
end

app/controllers/kublog/images_controller.rb
module Kublog
  class ImagesController < ApplicationController
    include XhrUpload::FileHelper
    
    before_filter  :set_image_file, :only => :create
    
    def create
      @image = Image.new(params[:image])
      respond_to do |format|
        if @image.save
          format.json { render :json => @image }
        else
          format.json { render :json => @image.errors.messages, :status => :unprocessable_entity }
        end
      end
    end
    
    def update
      @image = Image.find(params[:id])
      respond_to do |format|
        if @image.update_attributes(params[:image])
          format.json { render :json => @image }
        else
          format.json { render :json => @image.errors.messages, :status => :unprocessable_entity }
        end
      end
    end
    
    def destroy
      @image = Image.find(params[:id])
      @image.destroy
      respond_to do |format|
        format.json{ render :json => @image }
      end
    end
    
    private
    
    def set_image_file
      params[:image] ||= {:file => received_file}
    end
    
  end
end

app/controllers/kublog/notifications_controller.rb
module Kublog
  class NotificationsController < ApplicationController
    
    def preview
      @post = Post.new(params[:post])
      @preview = Notification.email_template(@post)
      respond_to do |format|
        format.json { render :json => {:preview => @preview }}
      end
    end
    
  end
end

app/controllers/kublog/posts_controller.rb
module Kublog
  class PostsController < ApplicationController
    
    skip_filter   :require_admin, :only => [:index, :show]
    
    def index
      @presenter = PostsPresenter.new
      respond_to do |format|
        format.html { }
        format.atom { render :layout => false, :content_type => 'text/xml' }
        format.rss  { render :layout => false, :content_type => 'text/xml' }
      end
    end
    
    def new
      @presenter = PostFormPresenter.new(Post.new)
    end
    
    def show
      post = Post.find(params[:id])
      @presenter = PostPresenter.new(post)
    end
    
    def create
      @post = current_user.posts.build(params[:post])
      if @post.save
        redirect_to @post
      else
        @presenter = PostFormPresenter.new(@post)
        render 'new'
      end
    end
    
    def edit
      @presenter = PostFormPresenter.new(Post.find(params[:id]))
    end
    
    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(params[:post])
        redirect_to @post
      else
        @presenter = PostFormPresenter.new(@post)
        render 'edit'
      end
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end
    
  end
end

app/helpers/kublog/application_helper.rb
module Kublog
  module ApplicationHelper
    
    ## Nifty generators errors helper code
    def error_messages_for(*objects)
      options = objects.extract_options!
      options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
      options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
      messages = objects.compact.map { |o| o.errors.full_messages }.flatten
      unless messages.empty?
        content_tag(:div, :class => "error_messages") do
          list_items = messages.map { |msg| content_tag(:li, msg) }
          content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
        end
      end
    end
    
  end
end

app/helpers/kublog/notifications_helper.rb
module Kublog
  module NotificationsHelper
  end
end

app/helpers/kublog/posts_helper.rb
module Kublog
  module PostsHelper
    VERSIONS = [['',''],
                ['original', 'Insert Original'], 
                ['small', 'Insert Small (140x140)'],
                ['thumb', 'Insert Thumbnail (54x54)']]
    
    def size_options
      @size_options ||= options_from_collection_for_select(VERSIONS, :first, :second)
    end
    
    def category_options(post)
      categories = Kublog::Category.all
      category_options = options_from_collection_for_select(categories, :id, :name, post.category.try(:id))
      options = "<option value='' class='blank'></option>"
      options += category_options      
      options += "<option value='create_new_category'>New category...</option>"
      options
    end
    
    def user_kinds
      Kublog.user_kinds
    end
    
    def missing_image_url
      Kublog::FileUploader.new.default_url
    end
    
    def display?(should)
      should ? 'display:block' : 'display:none'
    end
    
    def admin_comment?(comment)
      comment.admin? ? 'admin' : ''
    end
    
    def atom_url(presenter)
      presenter.category.nil? ? posts_url(:format => :atom) : category_url(presenter.category, :format => :atom)
    end
    
    def hide_if_no_invited_author(post)
      "display:none" unless display_invited_author_form?(post)
    end

    # To understand this, you need to know that
    # regardless if the user wants or not the invited author,
    # we need to build the invited author form so the form
    # is displayed appropiatly.
    # So asking if the post has an invited author is not enough
    def display_invited_author_form?(post)
      !(post.new_record? || post.invited_author.new_record?)
    end
  end
end

app/views/kublog/posts/_email_form.html.erb
<div class='field'>
  <%= check_box_tag   :email_notify, 1, notification.default?, 
                      :checked => false, :class => 'email_checkbox' %>
  <%= label_tag       :email_notify, t('.email_notification') %>     
  <% unless user_kinds.empty?  %>
    <div class='optional'>
      <ul>
        <% user_kinds.each do |user_kind|%>
          <li>
            <%= check_box_tag "#{nf.object_name}[roles][]", user_kind, nil %>
            <%= label_tag "#{nf.object_name}[roles][#{user_kind}]", user_kind.titleize %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>                     
  <div style='display:none' class='optional_lightbox'>
    <%= nf.hidden_field :kind, :disabled => !notification.default? %>
    <%= link_to '#', '#email-template', :class => 'submit_fancybox', :id => 'link-to-email-template' %>
    <div id="email-template">
      <h2><%= t('.format_email') %></h2>
      <div class='field'>
        <%= nf.text_area :content, :class => 'email_content', :disabled => !notification.default? %>
      </div>
      <div class='field'>
        <%= submit_tag t('.send_email'), :id => 'email_submit'  %> <%= t('.or') %>
        <%= link_to t('.cancel'), '#', :id => 'email_cancel' %>
      </div>
    </div>
  </div>
</div>

app/views/kublog/posts/_facebook_form.html.erb
<div class='field'>
  <%= check_box_tag :facebook_notify, 1, notification.default?, :class => 'trigger-optional' %> 
  <%= label_tag     :facebook_notify, t('.facebook_notification') %>
  <div class='optional' style='<%= display?(notification.default?) %>'>
    <%= nf.hidden_field :kind, :disabled => !notification.default? %>
    <%= nf.text_area    :content, :rows => 5, :cols => 10, :value => '', 
                        :disabled => !notification.default?, :class => 'small mimic' %>
    <small><%= t('.link_to_facebook')  %></small>
  </div>
</div>

app/views/kublog/posts/_form.html.erb
<%= form_for post, :html => {:class => 'post_form'} do |f| %>
  
  <%= error_messages_for post %>
  
  <div class="main-attributes">
    <div class='field'>
      <%= f.label :body %><br />
      <%= f.text_area :body, :class => 'editor' %>
      <%= render 'image_form' %>
    </div>
    <div class='field'>
      <%= f.label :title %> <br />
      <%= f.text_field :title, :class => 'original' %>
    </div>
    <div class='field'>
      <%= f.label :category_id %> <br />
      <%= select_tag 'post[category_id]', category_options(post).html_safe %>
    </div>
    <div class='field'>
      <%= check_box_tag 'post[want_invited_author]', "1", display_invited_author_form?(f.object) %>
      <%= f.label :want_invited_author %>
      <%= render :partial => 'invited_author_form', :locals => { :f => f } %>
    </div>
  </div>
  
  <div class='sharing-attributes'>
    <% notifications.each do |notification| %>
      <%= f.fields_for :notifications, notification do |nf| %>
        <%= render "#{notification.kind}_form", :notification => notification, :nf => nf %>
      <% end %>
    <% end %>
  </div>
  
  <div class='submit field'>
    <%= f.submit :id => 'create_post_button' %>
  </div>
  
<% end %>

app/views/kublog/posts/_image_form.html.erb
<div style='display:none'>
  <%= link_to '#', '#image-upload', :class => 'fancybox', :id => 'link-to-upload' %>
  <div id="image-upload">
    <h2><%= t('.insert_image') %></h2>
    <%= hidden_field_tag :image_id %>
    <div class='image-file field'>
      <%= file_field_tag :image, :class => 'upload' %><br /><br />
      <div class='container'>
        <span></span>
        <%= image_tag missing_image_url, :id => 'uploaded-file-placeholder' %>
      </div>
    </div>
    <div class='image-alt field'>
      <%= label_tag :image_alt, t('.alt') %><br />
      <%= text_field_tag :image_alt, '', :disabled => true  %>
    </div>
    <div class='image-size field'>
      <%= label_tag :insert_size, t('.insert_size') %><br />
      <%= select_tag :insert_size, size_options,  :disabled => true %>
    </div>
    <div class='field'>
      <%= submit_tag t('.insert_image'), :disabled => true %> 
      <%= t('.or') %> <%= link_to t('.cancel'), '#', :id => 'cancel-upload' %>
    </div>
  </div>  
</div>

app/views/kublog/posts/_invited_author_form.html.erb
<div style='<%= hide_if_no_invited_author(f.object) %>' id="invited_author">
  <%= f.fields_for :invited_author do |i| %>
    <div>
      <%= i.label :name %><br/>
      <%= i.text_field :name %>
    </div>
    <div>
      <%= i.label :email %><br/>
      <%= i.text_field :email %>
    </div>
  <% end %>
</div>

app/views/kublog/posts/_twitter_form.html.erb
<div class='field'>
  <%= check_box_tag :twitter_notify, 1, notification.default?, :class => 'trigger-optional' %> 
  <%= label_tag     :twitter_notify, t('.twitter_notification') %>
  <div class='optional' style='<%= display?(notification.default?) %>'>
    <span class='chars_left'>129</span>
    <%= nf.hidden_field :kind, :disabled => !notification.default? %>
    <%= nf.text_area    :content, :rows => 5, :cols => 10, :maxlength => 129, :value => '', 
                        :disabled => !notification.default?, :class => 'small mimic' %> 
    <small><%= t('.link_to_twitter')  %></small>
  </div>
</div>

app/views/kublog/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', :post => @presenter.post, :notifications => @presenter.notifications %>

app/views/kublog/posts/index.html.erb
<div class='post-actions'>
  <% if is_admin? %>
    <h2><%= t('.actions') %></h2>
    <ul>
      <li><%= link_to 'New Post', new_post_path %></li>
    </ul>
  <% end %>
  <% unless @presenter.categories.empty? %>
    <h2><%= t('.categories') %></h2>
    <ul id='categories'>
      <% @presenter.categories.each do |category|%>
        <li>
          <%= link_to category, category %> 
          <% if is_admin? %>
            <small>
              (<%= link_to t('.edit'), '#', :class => 'edit', 'data-prompt' => t('.edit_category_prompt') %> | 
               <%= link_to t('.delete'), '#', :class=> 'delete', 'data-confirm' => t('.category_delete_confirm')%>)
            </small>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

<% @presenter.posts.each do |post| %>  
  <div class='post'>
    <%= link_to content_tag(:h2, post.title), quickie_path(post), :class => 'post-title' %>
    <span class='published-at'>
      <%= l post.updated_at, :format => :short %>
    </span>
    <div class='post-body'>
      <%= post.body.html_safe %>
    </div>
  </div>
<% end %>

app/views/kublog/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', :post => @presenter.post, :notifications => @presenter.notifications %>

app/views/kublog/posts/show.html.erb
<div class='post-actions'>
  <h2><%= t('.post_actions') %></h2>
    <ul>
      <% if is_admin? %>
        <li><%= link_to t('.edit'),  [:edit, @presenter.post] %></li>
        <li><%= link_to t('.delete'), @presenter.post, :method => :delete, :confirm => t('.confirm') %></li>
      <% end %>
      <li> <%= link_to 'All posts', posts_path %></li>
    </ul>
</div>
<div class='post-title'>
  <h1><%= @presenter.post %></h1>
  <span class='published-at'><%= l @presenter.post.updated_at, :format => :short %></span>
  <span>Escrito por <%= @presenter.post.author %></span>
</div>
<div class='post-pody'>
  <%= @presenter.post.body.html_safe %>
</div>
<div class='post-comments'>
  <% @presenter.comments.each do |comment| %>
    <div class='comment <%= admin_comment?(comment) %>'>
      <h4><%= comment.author %></h4>
      <p class='body'><%= comment.body %></p>
      <span><%= l comment.created_at, :format => :short %></span>
      <% if is_admin? %>
        <div class='admin-actions'>
          <%= link_to t('.delete'), post_comment_path(@presenter.post, comment), 
                                    :method => :delete, :confirm => t('.confirm'), 
                                    :class=> 'delete' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class='new-comment'>
  <h2><%= t('.new_comment') %></h2>
  <%= form_for [@presenter.post, Kublog::Comment.new], :remote => true do |f| %>
    <%= f.text_area :body, :rows => 5, :cols => 20, :class => 'small' %> <br />
    <% unless current_user %>
      <%= f.label :author_name %><br />
      <%= f.text_field :author_name %> <br />
      <%= f.label :author_email %><br />
      <%= f.text_field :author_email %> <br />
    <% end %>
    <%= f.submit %>
  <% end %>
</div>